"""Clinical integration workspace over already-authorized Szondi3 outputs.

This module is the product seam between Longitudinal Comparison and the future
Clinician Working Report. It composes audited case projections, adjacent
longitudinal comparisons, and explicit clinician-authored context without changing
P1 results, activating new P2B claims, or treating clinician context as Szondian
evidence.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from .clinician_report_projection import (
    ClinicianReportProjection,
    project_clinician_report,
)
from .longitudinal_comparison import (
    CaseComparisonResult,
    LongitudinalCaseRef,
    compare_clinical_case_sequence,
)


@dataclass(frozen=True, slots=True)
class ClinicianContextItem:
    """Explicit external case context authored by the clinician.

    Context is preserved for clinical integration but is not promoted to case facts,
    executable Szondi claims, canonical evidence, or release provenance.
    """

    label: str
    text: str
    authorship: str = "CLINICIAN_INPUT"
    epistemic_role: str = "EXTERNAL_CASE_CONTEXT_NOT_SZONDI_EVIDENCE"

    def __post_init__(self) -> None:
        if not isinstance(self.label, str) or not self.label.strip():
            raise ValueError("Clinician context label must be a non-empty string")
        if not isinstance(self.text, str) or not self.text.strip():
            raise ValueError("Clinician context text must be a non-empty string")


@dataclass(frozen=True, slots=True)
class ClinicianAuthoredSynthesis:
    """Manual higher-order clinical synthesis, never generated by this module."""

    text: str | None
    authorship: str = "MANUAL_CLINICIAN_INPUT_ONLY"


@dataclass(frozen=True, slots=True)
class IntegratedAssessment:
    """One case identity paired with its audited clinician-facing projection."""

    case_id: str
    projection: ClinicianReportProjection


@dataclass(frozen=True, slots=True)
class ClinicalIntegration:
    """Deterministic workspace for clinician-led integration.

    ``history`` remains in the caller-supplied order; ``current`` is the assessment
    being integrated now. ``longitudinal`` contains only adjacent comparisons across
    history + current. No semantic conclusion is added to those structural diffs.
    """

    history: tuple[IntegratedAssessment, ...]
    current: IntegratedAssessment
    longitudinal: tuple[CaseComparisonResult, ...]
    clinician_context: tuple[ClinicianContextItem, ...]
    clinician_synthesis: ClinicianAuthoredSynthesis

    @property
    def assessment_ids(self) -> tuple[str, ...]:
        return tuple(item.case_id for item in self.history) + (self.current.case_id,)


def _project(case: LongitudinalCaseRef) -> IntegratedAssessment:
    return IntegratedAssessment(
        case_id=case.case_id,
        projection=project_clinician_report(case.run),
    )


def integrate_clinical_case(
    current: LongitudinalCaseRef,
    *,
    prior_cases: Sequence[LongitudinalCaseRef] = (),
    clinician_context: Sequence[ClinicianContextItem] = (),
    clinician_synthesis: str | None = None,
) -> ClinicalIntegration:
    """Compose current Szondi output, ordered history, and clinician input.

    The function deliberately does not interpret longitudinal change and does not
    feed clinician context back into P1/P2B. Any provenance/comparability issue
    already exposed by ``Longitudinal Comparison`` remains visible in the returned
    comparisons for clinician inspection.
    """
    if not isinstance(current, LongitudinalCaseRef):
        raise TypeError("current must be a LongitudinalCaseRef")

    history_refs = tuple(prior_cases)
    if any(not isinstance(item, LongitudinalCaseRef) for item in history_refs):
        raise TypeError("prior_cases must contain only LongitudinalCaseRef objects")

    sequence = history_refs + (current,)
    case_ids = tuple(item.case_id for item in sequence)
    if len(case_ids) != len(set(case_ids)):
        raise ValueError("Clinical integration requires unique case_id values")

    context_items = tuple(clinician_context)
    if any(not isinstance(item, ClinicianContextItem) for item in context_items):
        raise TypeError("clinician_context must contain only ClinicianContextItem objects")

    if clinician_synthesis is not None:
        if not isinstance(clinician_synthesis, str):
            raise TypeError("clinician_synthesis must be a string or None")
        if not clinician_synthesis.strip():
            raise ValueError("clinician_synthesis cannot be blank")

    projected_history = tuple(_project(item) for item in history_refs)
    projected_current = _project(current)
    longitudinal = (
        compare_clinical_case_sequence(sequence)
        if len(sequence) >= 2
        else ()
    )

    return ClinicalIntegration(
        history=projected_history,
        current=projected_current,
        longitudinal=longitudinal,
        clinician_context=context_items,
        clinician_synthesis=ClinicianAuthoredSynthesis(text=clinician_synthesis),
    )
